language: ruby
sudo: false
test: 'true'
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: CR1YQUm7fSFae/fFdgIDOm7L8466YspGUZS8JNS84lQJCBzJUWeCktB5zRo0UWsviCw/BbbGLXsX9AzOpvoENGqGe2ZveNuC/qicS1sX3Z4gXxUx0gDHfGWR16fIvbTXl1EacwcWALyY0NVsH0QPOlJatGXrNLpo0fTXMrJngocz5ShPStQnJRydpkFUFxi09cRYynzIq/Wj0zmV/0clwHnm4bMlJ3satvun8z9Lx+/eEdpPtZofjRdcmd/KWa/n4HrP4ONz3p7AYQNNUKu6XBS0sAqBD0rAQtx4wT6pg733CpOtuWfgwEVt+X8pWhrgZY4aIPkYNvw7TsHYdRWRMGZ6XSe+IXsfSSal5VJgLp8zpEqnr9uaANV3Nk+l6RnR/Gsl/tY0V7eI2orJEy8OpGkxjqnQyBNzrQCtA+3lzAC14CDJ7PYAZaQsrF3owAeWUWE3CtHleTRQA8Ibp4M9ZEM+x5Y1ilRo8Dye/4rB4bOn/qPGE4qdNFSfHZZT3YGnPxxaqCHl36nkZbDY76/lgsjXeXZ8XF6k+OTZQBnx3ZWj6+MM3Q8m40ectHY/MgY0dCeudsLCoWObMqkkB0ruep98oZSyNWuunziDMMAxel4iYaQ/Mh/0YTlAGJOO70YtEPazdBAI8NSl6lM7cpDOIYG/XplIDUx9aV3/gyU3UBI=
  app: praisinator-web
  on:
    repo: with-our-powers-combined/praisinator-web
