default: &default
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: 'praisinator-web_development'

test:
  <<: *default
  database: 'praisinator-web_test'

production:
  url: <%= ENV['DATABASE_URL'] || CFENV.dig('praisinator-postgresql', 'uri') %>

