default: &default
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: 'praisinator-web_development'

test:
  <<: *default
  database: 'praisinator-web_test'

production:
  url: postgresql://<%= CFENV['praisinator-postgres']['public_hostname'] %>/compose
  username: <%= CFENV['praisinator-postgres']['username'] %>
  password: <%= CFENV['praisinator-postgres']['password'] %>
  <<: *default

